import { Category, Habit, Task, Goal, Reminder, UserSettings } from '../types';
import { getTodayString } from './dateUtils';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'health', name: 'Health & Fitness', color: '#10b981', icon: 'Activity' },
  { id: 'focus', name: 'Deep Work & Career', color: '#3b82f6', icon: 'Briefcase' },
  { id: 'mind', name: 'Mindfulness & Growth', color: '#8b5cf6', icon: 'Brain' },
  { id: 'habits', name: 'Daily Routines', color: '#f59e0b', icon: 'Sparkles' },
  { id: 'finance', name: 'Finance & Admin', color: '#ec4899', icon: 'Wallet' },
];

export const DEFAULT_SETTINGS: UserSettings = {
  theme: 'oled',
  soundEnabled: true,
  alarmVolume: 0.7,
  defaultAlarmSound: 'bell',
  notificationsEnabled: true,
  weekStartsOnMonday: true,
  pomodoroWorkMinutes: 25,
  pomodoroBreakMinutes: 5,
  pomodoroLongBreakMinutes: 15,
  ambientSound: 'none',
  ambientVolume: 0.3,
};

export function getInitialPresets() {
  const today = getTodayString();

  const habits: Habit[] = [
    {
      id: 'h-1',
      title: 'Morning Hydration',
      description: 'Drink 500ml of water right after waking up',
      category: 'health',
      color: '#06b6d4',
      icon: 'Droplets',
      type: 'number',
      targetValue: 2000,
      unit: 'ml',
      frequency: { type: 'daily' },
      timeOfDay: 'morning',
      reminderTime: '07:30',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'h-2',
      title: 'Deep Work Focus Block',
      description: 'Uninterrupted creative/coding focus with notifications off',
      category: 'focus',
      color: '#3b82f6',
      icon: 'Flame',
      type: 'timer',
      targetValue: 45,
      unit: 'mins',
      frequency: { type: 'specific_days', days: [1, 2, 3, 4, 5] },
      timeOfDay: 'morning',
      reminderTime: '09:00',
      goalId: 'g-1',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'h-3',
      title: 'Read Non-Fiction',
      description: 'Expand knowledge by reading at least 20 pages',
      category: 'mind',
      color: '#8b5cf6',
      icon: 'BookOpen',
      type: 'number',
      targetValue: 20,
      unit: 'pages',
      frequency: { type: 'daily' },
      timeOfDay: 'evening',
      reminderTime: '21:00',
      goalId: 'g-2',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'h-4',
      title: 'Physical Workout / Movement',
      description: 'Gym, calisthenics, running or brisk walk',
      category: 'health',
      color: '#10b981',
      icon: 'Dumbbell',
      type: 'boolean',
      frequency: { type: 'specific_days', days: [1, 2, 3, 4, 5, 6] },
      timeOfDay: 'afternoon',
      reminderTime: '17:00',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'h-5',
      title: 'Nightly Reflection & Planning',
      description: 'Log accomplishments and organize top 3 priorities for tomorrow',
      category: 'habits',
      color: '#f59e0b',
      icon: 'Moon',
      type: 'boolean',
      frequency: { type: 'daily' },
      timeOfDay: 'evening',
      reminderTime: '22:00',
      createdAt: new Date().toISOString(),
    },
  ];

  const tasks: Task[] = [
    {
      id: 't-1',
      title: 'Deep Focus Sprint: Core Feature Architecture',
      description: 'Design and build the main component layout and time blocking planner',
      category: 'focus',
      priority: 'high',
      status: 'in_progress',
      date: today,
      startTime: '09:30',
      endTime: '11:30',
      durationMinutes: 120,
      subtasks: [
        { id: 'st-1', title: 'Draft schema & state management', completed: true },
        { id: 'st-2', title: 'Implement drag-and-drop timeline', completed: false },
        { id: 'st-3', title: 'Wire alarm triggers and chimes', completed: false },
      ],
      goalId: 'g-1',
      createdAt: new Date().toISOString(),
    },
    {
      id: 't-2',
      title: 'Midday Re-energize & Healthy Lunch',
      description: 'Step away from screens, eat a nutritious meal',
      category: 'health',
      priority: 'medium',
      status: 'todo',
      date: today,
      startTime: '13:00',
      endTime: '14:00',
      durationMinutes: 60,
      subtasks: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: 't-3',
      title: 'Review Goal Milestones & Weekly Analytics',
      description: 'Reflect on habit consistency and adjust timelines for next week',
      category: 'mind',
      priority: 'low',
      status: 'todo',
      date: today,
      startTime: '18:00',
      endTime: '18:45',
      durationMinutes: 45,
      subtasks: [],
      goalId: 'g-2',
      createdAt: new Date().toISOString(),
    }
  ];

  const goals: Goal[] = [
    {
      id: 'g-1',
      title: 'Master Consistent Deep Work & High Productivity',
      description: 'Accumulate 100+ hours of focused deep work sessions without burnout',
      category: 'focus',
      color: '#3b82f6',
      icon: 'Zap',
      targetDate: '2026-12-31',
      status: 'active',
      milestones: [
        { id: 'm-1', title: 'Complete 10 consecutive focus days', completed: true },
        { id: 'm-2', title: 'Eliminate social media during work hours', completed: true },
        { id: 'm-3', title: 'Log 50 total hours of deep work', completed: false },
        { id: 'm-4', title: 'Reach 100 total hours milestone', completed: false },
      ],
      linkedHabitIds: ['h-2'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'g-2',
      title: 'Read 12 Impactful Books & Learn Continuously',
      description: 'Build lifelong reading discipline with 20 pages every single day',
      category: 'mind',
      color: '#8b5cf6',
      icon: 'BookOpen',
      targetDate: '2026-12-31',
      status: 'active',
      milestones: [
        { id: 'm-21', title: 'Atomic Habits by James Clear', completed: true },
        { id: 'm-22', title: 'Deep Work by Cal Newport', completed: true },
        { id: 'm-23', title: 'Thinking, Fast and Slow', completed: false },
        { id: 'm-24', title: 'Show Your Work by Austin Kleon', completed: false },
      ],
      linkedHabitIds: ['h-3'],
      createdAt: new Date().toISOString(),
    },
  ];

  const reminders: Reminder[] = [
    {
      id: 'r-1',
      title: 'Morning Kickoff & Water Hydration',
      description: 'Drink 500ml water and review daily tasks',
      type: 'alarm',
      time: '07:30',
      recurring: { type: 'daily' },
      sound: 'bell',
      enabled: true,
      sourceId: 'h-1',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'r-2',
      title: 'Stand Up & Stretch Break',
      description: 'Relax eyes and walk around for 5 mins',
      type: 'reminder',
      time: '11:30',
      recurring: { type: 'daily' },
      sound: 'zen',
      enabled: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'r-3',
      title: 'Daily Shutdown & Evening Plan',
      description: 'Wrap up tasks, review habits, and wind down',
      type: 'alarm',
      time: '21:30',
      recurring: { type: 'daily' },
      sound: 'gentle',
      enabled: true,
      createdAt: new Date().toISOString(),
    },
  ];

  return { habits, tasks, goals, reminders, categories: DEFAULT_CATEGORIES, settings: DEFAULT_SETTINGS };
}
